#!/bin/bash

# Script to create date snapshot all mirrors from a release

#    create-release-snapshot
#    Copyright (C) 2015 Rudy Gevaert <rudy.gevaert@ugent.be>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.



if [ -z "$1" ]
then
  echo "Usage: $0 <release-name|mirror-name> [date]"
  exit 1
fi


if [ -z "$2" ]
then
  date=`date +%Y%m%d-%T`
else
  date=$2
fi

case "$1" in
  wheezy|jessie)
    mirrors=`aptly mirror list -raw | grep ^$1 | egrep "contrib|main|non\-free|security"`
    ;;
  trusty)
    mirrors=`aptly mirror list -raw | grep ^$1 | egrep "main|multiverse|restricted|universe"`
    ;;
  *)
    mirrors=$1
    ;;
esac

if [ -z "$mirrors" ]
then
  echo mirror list empty
  exit 1
fi

for mirror in $mirrors
do
  aptly snapshot create ${mirror}-${date} from mirror $mirror
done
