#!/bin/bash


# Script that gets shows the diff between published repos

#    Copyright (C) 2015 Rudy Gevaert <rudy.gevaert@ugent.be>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.



if [ -z "$2" ]
then
  echo "USage: $0 published-name-A published-name-B"
  exit 1
fi

SNAPSHOT_A=`aptly publish list | grep " $1" | sed -e 's/.*\[\(.*\)\].*/\1/'`
SNAPSHOT_B=`aptly publish list | grep " $2" | sed -e 's/.*\[\(.*\)\].*/\1/'`
aptly snapshot diff $SNAPSHOT_A $SNAPSHOT_B
