#!/bin/bash

# Script to trigger an update on all mirrors from a distribution

#    update-release-mirror
#    Copyright (C) 2015 Rudy Gevaert <rudy.gevaert@ugent.be>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


if [ -z "$1" ]
then
  echo "USage: $0 <release-name|mirror-name>"
  exit 1
fi

for mirror in `aptly mirror list -raw | grep ^$1`
do
  aptly mirror update $mirror
done
